# MASTERING PYTHON FUNCTIONS

In [1]:
# EXERCISE 1; IDEA MIA:

def calculate_area(width,height):
    result = width * height
    return result

calculate_area(2,3)    

6

In [2]:
# IDEA PROF

def calculate_area(h,w):
    return h*w

calculate_area(4,5)

20

In [3]:
my_list = [1,2,3,4,5]

In [4]:
my_list[-1]

5

In [8]:
def first_and_last(l):
    return l[0], l[-1]


first_and_last(my_list)

(1, 5)

# IMPORTING AND UTILIZING PYTHON MODULES AND LIBRARIES

In [10]:
# EXERCISE 1

import math

In [11]:
math.sqrt(1024)

32.0

In [15]:
import datetime as dt

now = dt.datetime.now()
now

datetime.datetime(2026, 2, 18, 9, 55, 25, 370717)

In [16]:
now.strftime("%d/%m/%Y %H:%M") # m = month, M = minutes

'18/02/2026 09:55'

In [17]:
# EXERCISE 2

import random

random.randint(1,10)

5

In [18]:
# EXERCISE 3

# REQUESTS library

In [19]:
!pip install requests

In [21]:
# url = ""

url = "https://google.com"

In [22]:
import requests

response = requests.get(url)

In [23]:
response.text

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="it"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="9nTFdInft4AdUdxKp4KoiA">(function(){var _g={kEI:\'gYKVaeCjPNC0ptQPhJeBqQI\',kEXPI:\'0,18168,1286035,2935842,14111,34680,30022,94323,266578,270475,5262487,15,36811391,25228681,152387,8935,3003,45184,8040,39771,74608,709,15099,8165,153158,33385,26230,25591,9878,15419,21042,9921,8068,10,2676,202,9924,1760,16179,15899,9997,15501,1383,4,1514,3355,197,5813,2,4205,8,1786,16,14291,2,898,2207,5089,19,3007,15,781,32270,98,4255,1035,4302,320,525,2047,1,1,9,14,1549,3,5941,2757,4,15193,4,2171,71,241,297,5,1113,389,4,2647,5,5568,298,9253,1275,7,2840,2,3859,8510,2,5724,9,602,1649,4,3386,2543,4555,1,2,827,3,1359,3,2355,2555,70,10,215,441,158,2,1645,191,4,1928,2,1636,544,4,1568,113,921,1398,187,2105,5,259,5,197,2130,236,19

In [24]:
# EXERCISE 4

# OS Library

In [25]:
import os
os.getcwd() # cwd = current working directory

'C:\\Users\\huawei\\source\\masterds01\\day3'

# EXERCISES WITH THE CSV LIBRARY

# CSV LIBRARY

In [31]:
import csv

with open("my_data.csv") as f:
    reader = csv.reader(f) # iterator
    for row in reader:
        print(row)
    

['id', 'name', 'age', 'city']
['1', 'Alice', '34', 'New York']
['2', 'Bob', '23', 'Los Angeles']
['3', 'Charlie', '40', 'Chicago']
['4', 'Diana', '28', 'Houston']
['5', 'Evan', '19', 'Phoenix']


In [32]:
import csv

with open("my_data.csv") as f:
    reader = csv.DictReader(f) # iterator
    for row in reader:
        print(row)
    

{'id': '1', 'name': 'Alice', 'age': '34', 'city': 'New York'}
{'id': '2', 'name': 'Bob', 'age': '23', 'city': 'Los Angeles'}
{'id': '3', 'name': 'Charlie', 'age': '40', 'city': 'Chicago'}
{'id': '4', 'name': 'Diana', 'age': '28', 'city': 'Houston'}
{'id': '5', 'name': 'Evan', 'age': '19', 'city': 'Phoenix'}


import csv

with open("my_data.csv") as f:
    reader = csv.DictReader(f) # iterator
    for row in reader:
        print(row["id"],row["city"])

In [34]:
"""
import csv
from io import StringIO

reader = csv.DictReader(StringIO(response.txt) # iterator
for row in reader:
    print(row["description"],row["value"])

"""

SyntaxError: '(' was never closed (2340773414.py, line 5)

# Activities with Tkinter

In [36]:
import tkinter as tk

In [42]:
root = tk.Tk() 

In [43]:
root.title("My First Tkinter Window")

''

In [50]:
root.mainloop() # da runnare alla fine

In [44]:
welcome_label = tk.Label(root, text = "Welcome to Tkinter")

In [45]:
welcome_label.pack()

In [47]:
def on_button_click():
    welcome_label.config(text = "Button clicked")

In [48]:
click_me_button = tk.Button(root, text = "Click me!", command = on_button_click)

In [49]:
click_me_button.pack()

# Numerical Computing with NumPy

In [51]:
import numpy as np

In [55]:
my_array = np.array([1, 10, -5, 20])
my_array

array([ 1, 10, -5, 20])

In [58]:
print(f"The mean is {my_array.mean()}")
print(f"The mean is {my_array.std()}")

The mean is 6.5
The mean is 9.447221813845593


In [59]:
print(f"Multiplication by 2: {my_array*2}")

Multiplication by 2: [  2  20 -10  40]


In [61]:
my_arr_4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]]) # bidimensional array, it's 4 by 3
my_arr_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
my_arr_4x3 *4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [64]:
print(f"Inverted matrix:\n{my_arr_4x3.T}")

Inverted matrix:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [66]:
print(f"elements in this matrix: {my_arr_4x3.size}")

elements in this matrix: 12


In [67]:
print(f"shape of this matrix: {my_arr_4x3.shape}")

shape of this matrix: (4, 3)


In [79]:
np.random.randint(100,200)

179

In [82]:
random_integers = np.random.randint(100,200,20)
random_integers

array([107, 126, 190, 109, 182, 176, 195, 178, 154, 183, 101, 120, 145,
       130, 191, 108, 174, 139, 177, 123], dtype=int32)

In [85]:
random_integers % 2 # list of 0 and 1, 1 means odd, 0 means even

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1],
      dtype=int32)

In [86]:
random_integers % 2 == 0  # i want only the numbers that are even, this is the condition, vedi sotto

array([False,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True, False,  True, False,  True,  True, False,
       False, False])

In [87]:
even_numbers =random_integers[random_integers % 2 == 0]
even_numbers

array([126, 190, 182, 176, 178, 154, 120, 130, 108, 174], dtype=int32)

In [88]:
sliced_array = even_numbers[2:8] # just a portion for this array
sliced_array 

array([182, 176, 178, 154, 120, 130], dtype=int32)

In [96]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)

print(f"The two arrays are:\n{arr1}\n{arr2}")

The two arrays are:
[6 2 2 9]
[5 0 3 9]


In [97]:
print(f"The sum of the two arrays is {arr1+arr2}")
print(f"The difference of the two arrays is {arr1-arr2}")
print(f"The multiplication of the two arrays is {arr1*arr2}") 

The sum of the two arrays is [11  2  5 18]
The difference of the two arrays is [ 1  2 -1  0]
The multiplication of the two arrays is [30  0  6 81]


In [98]:
np.dot(arr1,arr2)

np.int32(117)

In [99]:
(arr1*arr2).sum()

np.int64(117)

In [100]:
# Exercise 5

In [102]:
import numpy as np
dataset = np.genfromtxt("data.csv",delimiter = ";")
dataset

array([[83., 21., 90., 85., 98., 73., 17., 40., 70.],
       [51., 30., 70., 71., 46., 57., 42., 96., 76.],
       [ 7.,  5., 92., 76., 29., 94., 50.,  4., 62.],
       [18.,  3., 86., 17., 24., 19.,  6., 94., 13.],
       [43., 81., 15., 43., 71., 69., 29., 23., 12.],
       [65., 29., 19., 33., 63., 58., 65., 25., 19.],
       [59., 74., 98., 20.,  6., 73., 62., 58., 31.],
       [40., 86., 54., 43., 27.,  4., 81., 47., 25.],
       [58., 50., 98., 51., 74., 84., 46., 26., 75.],
       [67., 79., 99., 83.,  1., 95., 67., 82.,  6.],
       [98., 92., 35., 75., 73., 70., 97., 32., 26.],
       [75., 30., 11., 47., 36., 27., 67., 17., 67.],
       [36., 35., 71., 38., 25., 75., 65., 28.,  4.]])

In [103]:
dataset.sum()

np.float64(5958.0)

In [104]:
column_index = 0
column_data = dataset[:,column_index]
column_data

array([83., 51.,  7., 18., 43., 65., 59., 40., 58., 67., 98., 75., 36.])